#!/bin/bash

in_progress_job_ids() {
  local branch_name

  branch_name="$1"

  gh run list \
    --branch $branch_name \
    --status in_progress \
    --jq 'map(select(.name == "Verify PR"))' \
    --json "name,databaseId"
}

latest_in_progress_job_id() {
  local branch_name

  branch_name="$(git rev-parse --abbrev-ref HEAD)" || return 1

  in_progress_job_ids "$branch_name" \
  | jq --raw-output ".[0].databaseId"
}

err_echo() {
  local message
  message="$1"

  echo "$message" 1>&2
}

view_log() {
  local id
  id="$1"

  gh run view "$id" --log | cat
}

main() {
  local number exit_code

  id="$(latest_in_progress_job_id)"
  exit_code=$?

  if [ $exit_code -ne 0 ]; then
    err_echo "Could not find an in progress verification job, trying again in 1 second"
    sleep 1 || exit 1
    id="$(latest_in_progress_job_id)"
    exit_code=$?
  fi

  gh run watch --exit-status "$id" || view_log "$id"
}
main "$@"
